Add binary operato rule to config file
Buzzoole/pre-commit-php pull request #1
Opened 2019-03-22 10:47 UTC by antoniofrignani

2019-03-22 13:57 UTC, pacoogle requested changes
Descrizione della PR?

2019-03-22 14:11 UTC, antoniofrignani commented
@pacoogle aggiunta

2019-03-22 14:31 UTC, pacoogle approved these changes
💯

2019-03-22 19:43 UTC, giefferre approved these changes
🔝

2019-03-25 09:06 UTC, gaedelprete approved these changes

2019-03-27 11:14 UTC, merged